### ISSUE TITLE
 could not compile `uefi`

### ISSUE THREAD

**Issue by luyikk** [rust-osdev/bootloader#178]
``` shell
~/desktop/basic$ cargo kimage
    Updating crates.io index
    Finished dev [unoptimized + debuginfo] target(s) in 0.52s
     Running `cargo run --package simple_boot -- target/x86_64-custom/debug/basic_example --no-run`
   Compiling json v0.12.4
   Compiling locate-cargo-manifest v0.2.2
   Compiling bootloader-locator v0.0.4
   Compiling simple_boot v0.1.0 (~/desktop/basic/simple_boot)
    Finished dev [unoptimized + debuginfo] target(s) in 1.37s
     Running `target/debug/simple_boot target/x86_64-custom/debug/basic_example --no-run`
error[E0432]: unresolved import `core::ops::FromResidual`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/uefi-0.11.0/src/result/status.rs:4:24
  |
4 |     ops::{ControlFlow, FromResidual, Try},
  |                        ^^^^^^^^^^^^ no `FromResidual` in `ops`

error[E0437]: type `Output` is not a member of trait `Try`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/uefi-0.11.0/src/result/status.rs:179:5
    |
179 |     type Output = Completion<()>;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `Try`

error[E0437]: type `Residual` is not a member of trait `Try`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/uefi-0.11.0/src/result/status.rs:180:5
    |
180 |     type Residual = StatusResidual;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `Try`

error[E0407]: method `branch` is not a member of trait `Try`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/uefi-0.11.0/src/result/status.rs:182:5
    |
182 | /     fn branch(self) -> ControlFlow<Self::Residual, Self::Output> {
183 | |         match NonZeroUsize::new(self.0) {
184 | |             Some(r) => ControlFlow::Break(StatusResidual(r)),
185 | |             None => ControlFlow::Continue(Completion::from(self)),
186 | |         }
187 | |     }
    | |_____^ not a member of trait `Try`

error[E0407]: method `from_output` is not a member of trait `Try`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/uefi-0.11.0/src/result/status.rs:189:5
    |
189 | /     fn from_output(output: Self::Output) -> Self {
190 | |         output.status()
191 | |     }
    | |_____^ not a member of trait `Try`

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0407, E0432, E0437.
For more information about an error, try `rustc --explain E0407`.
error: could not compile `uefi`

To learn more, run the command again with --verbose.
error: build failed
thread 'main' panicked at 'assertion failed: cmd.status()?.success()', src/bin/builder.rs:112:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'build failed', simple_boot/src/main.rs:63:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by bjorn3** [comment]
Try updating your nightly. The `uefi` crate depends on a nightly feature that recently changed.

**Comment by luyikk** [comment]
thanks
